name: Generate a build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Webhook build
    if: ${{ (github.repository != 'neonhms/neon_hms_column_v1') && (true) }}
    steps:
      - run: |
          git config --global user.email "ikechianya1@gmail.com"
          git config --global user.name "Ikechi Anya"

      - name: Git-checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install all dependencies
        run: yarn install --legacy-peer-deps

      - name: Stop ignoring build in gitignore
        run: sed -i 's/build/# build/' .gitignore

      - name: Create build
        run: CI=false yarn build

      - name: Env file processes
        shell: bash
        run: |
          touch build/.env
          cp .env build/.env
          echo -e "\nENVIRONMENT=${{ vars.ENVIRONMENT }}" >> build/.env
          echo CLIENT_URL=${{ vars.CLIENT_URL }} >> build/.env
          echo MYS_HOST=${{ vars.HOST }} >> build/.env
          echo MYS_SECRET_DBUSER=${{ secrets.DBUSER }} >> build/.env
          echo MYS_SECRET_PASSWORD=${{ secrets.DBPASS }} >> build/.env
          echo WEBHOOK_GITHUB_SIGNATURE=${{ secrets.WEBHOOK_GITHUB_SIGNATURE }} >> build/.env

      - name: Set timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Africa/Lagos

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Webhook commit with build
        run:  |
          git add -A
          git commit -m 'webhook commit ${{ github.event.commits[0].message }}_${{ env.NOW }}'
          git push

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Remove build commit
        run:  |
          git rm -r build
          git add -A
          git commit -m 'remove-build-auto commit ${{ github.event.commits[0].message }}_${{ env.NOW }}'
          git push

      - name: Ignore build in gitignore
        run: sed -i 's/# build/build/' .gitignore

      - name: Ignore-build commit
        run:  |
          git add -A
          git commit -m 'final-auto commit ${{ github.event.commits[0].message }}_${{ env.NOW }}'
          git push
